#if !canImport(ObjectiveC)
import XCTest

extension AnalyzeSyntaxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnalyzeSyntaxTests = [
        ("testInitIndex", testInitIndex),
        ("testInitSchema", testInitSchema),
        ("testInitSchemaIndex", testInitSchemaIndex),
        ("testInitSchemaTable", testInitSchemaTable),
        ("testInitTable", testInitTable),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AnalyzeSyntaxTests.__allTests__AnalyzeSyntaxTests),
    ]
}
#endif
