#if !canImport(ObjectiveC)
import XCTest

extension SwiftQLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftQLTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftQLTests.__allTests__SwiftQLTests),
    ]
}
#endif
