#if !canImport(ObjectiveC)
import XCTest

extension SwiftQLiteTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftQLiteTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftQLiteTests.__allTests__SwiftQLiteTests),
    ]
}
#endif
